services:
  - type: web
    name: kabou-school-bot
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true
